/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'service-accounts': ServiceAccountAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    'content-briefs': ContentBrief;
    'marketing-email-templates': MarketingEmailTemplate;
    'marketing-campaigns': MarketingCampaign;
    users: User;
    'service-accounts': ServiceAccount;
    'automation-requests': AutomationRequest;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'content-briefs': ContentBriefsSelect<false> | ContentBriefsSelect<true>;
    'marketing-email-templates': MarketingEmailTemplatesSelect<false> | MarketingEmailTemplatesSelect<true>;
    'marketing-campaigns': MarketingCampaignsSelect<false> | MarketingCampaignsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'service-accounts': ServiceAccountsSelect<false> | ServiceAccountsSelect<true>;
    'automation-requests': AutomationRequestsSelect<false> | AutomationRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'zh' | 'es' | 'fr' | 'ja')
    | ('en' | 'zh' | 'es' | 'fr' | 'ja')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'zh' | 'es' | 'fr' | 'ja';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | ServiceAccount;
  jobs: {
    tasks: {
      importContent: TaskImportContent;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ServiceAccountAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Path without a leading slash, for example tools/word-counter.
   */
  slug: string;
  summary: string;
  template: 'content' | 'landing' | 'content-with-tool' | 'tool-first';
  workflowStatus: 'draft' | 'in-review' | 'approved' | 'archived';
  publishedAt?: string | null;
  layout?: (HeroBlock | RichTextBlock | CalloutBlock | FaqBlock | CtaBlock | ToolBlock)[] | null;
  /**
   * Search guidance is advisory. Only malformed URLs and missing required page fields block publishing.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    primaryQuery?: string | null;
    intent?: ('informational' | 'commercial' | 'transactional' | 'navigational') | null;
    secondaryQueries?:
      | {
          query: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional site-relative override, for example /guides/example.
     */
    canonicalPath?: string | null;
    schemaType?: ('WebPage' | 'Article' | 'HowTo' | 'FAQPage' | 'SoftwareApplication') | null;
    noIndex?: boolean | null;
    openGraphImage?: (number | null) | Media;
  };
  /**
   * Recorded automatically for API- and workflow-created content.
   */
  provenance?: {
    source: 'human' | 'api' | 'batch-import' | 'ai-workflow';
    workflowRunId?: string | null;
    model?: string | null;
    promptVersion?: string | null;
    sourceKeywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    generatedAt?: string | null;
    lastHumanEditAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  heading: string;
  lede?: string | null;
  alignment?: ('left' | 'center') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  heading?: string | null;
  body: string;
  tone?: ('note' | 'tip' | 'warning') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  heading: string;
  body?: string | null;
  label: string;
  /**
   * Use a site path, https URL, email link, or page anchor.
   */
  href: string;
  style?: ('primary' | 'secondary') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToolBlock".
 */
export interface ToolBlock {
  /**
   * Only developer-registered tools can run on public pages; arbitrary scripts are never accepted.
   */
  toolKey: 'word-counter' | 'percentage-calculator' | 'keyword-density';
  heading: string;
  description?: string | null;
  placement?: ('inline' | 'wide' | 'sticky-aside') | null;
  theme?: ('card' | 'quiet' | 'accent') | null;
  config?: {
    inputLabel?: string | null;
    defaultKeyword?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'tool';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * Enable only after this asset is ready to appear on a published page.
   */
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    social?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  summary: string;
  authors?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  workflowStatus: 'draft' | 'in-review' | 'approved' | 'archived';
  publishedAt?: string | null;
  layout?: (HeroBlock | RichTextBlock | CalloutBlock | FaqBlock | CtaBlock | ToolBlock)[] | null;
  /**
   * Search guidance is advisory. Only malformed URLs and missing required page fields block publishing.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    primaryQuery?: string | null;
    intent?: ('informational' | 'commercial' | 'transactional' | 'navigational') | null;
    secondaryQueries?:
      | {
          query: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional site-relative override, for example /guides/example.
     */
    canonicalPath?: string | null;
    schemaType?: ('WebPage' | 'Article' | 'HowTo' | 'FAQPage' | 'SoftwareApplication') | null;
    noIndex?: boolean | null;
    openGraphImage?: (number | null) | Media;
  };
  /**
   * Recorded automatically for API- and workflow-created content.
   */
  provenance?: {
    source: 'human' | 'api' | 'batch-import' | 'ai-workflow';
    workflowRunId?: string | null;
    model?: string | null;
    promptVersion?: string | null;
    sourceKeywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    generatedAt?: string | null;
    lastHumanEditAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-briefs".
 */
export interface ContentBrief {
  id: number;
  title: string;
  locale: 'en' | 'zh' | 'es' | 'fr' | 'ja';
  status: 'idea' | 'researched' | 'ready' | 'used' | 'archived';
  primaryKeyword: string;
  secondaryKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  intent?: ('informational' | 'commercial' | 'transactional' | 'navigational') | null;
  audience?: string | null;
  outline: string;
  internalLinkTargets?: string | null;
  workflowRunId?: string | null;
  sourceData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-email-templates".
 */
export interface MarketingEmailTemplate {
  id: number;
  name: string;
  key: string;
  logoUrl?: string | null;
  accentColor: string;
  pageBackgroundColor: string;
  contentBackgroundColor: string;
  defaultFromName?: string | null;
  defaultReplyTo?: string | null;
  footerText?: string | null;
  /**
   * A valid sender postal address. The SaaS adds this and its unsubscribe link to every marketing message.
   */
  companyAddress: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-campaigns".
 */
export interface MarketingCampaign {
  id: number;
  internalName: string;
  /**
   * Stable launch identity, for example 2026-08-product-update.
   */
  campaignKey: string;
  locale: 'en' | 'zh' | 'es' | 'fr' | 'ja';
  /**
   * A consent topic resolved by the SaaS; recipient addresses never enter the Studio.
   */
  audienceTopic: string;
  filterAudienceByLocale?: boolean | null;
  template: number | MarketingEmailTemplate;
  subject: string;
  preheader?: string | null;
  content: (
    | EmailHeadingBlock
    | EmailTextBlock
    | EmailImageBlock
    | EmailButtonBlock
    | EmailDividerBlock
    | EmailSpacerBlock
  )[];
  fromName?: string | null;
  replyTo?: string | null;
  workflowStatus: 'draft' | 'in-review' | 'approved' | 'archived';
  /**
   * Optional. Launch queues the campaign now and the SaaS waits until this time.
   */
  scheduledAt?: string | null;
  launchStatus?: ('not-launched' | 'scheduled' | 'queued' | 'completed' | 'canceled' | 'failed') | null;
  launchedAt?: string | null;
  recipientCount?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailHeadingBlock".
 */
export interface EmailHeadingBlock {
  text: string;
  level: '1' | '2' | '3';
  align: 'left' | 'center';
  id?: string | null;
  blockName?: string | null;
  blockType: 'heading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailTextBlock".
 */
export interface EmailTextBlock {
  /**
   * Plain text with line breaks. HTML is intentionally not accepted.
   */
  text: string;
  align: 'left' | 'center';
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailImageBlock".
 */
export interface EmailImageBlock {
  url: string;
  alt?: string | null;
  linkUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailButtonBlock".
 */
export interface EmailButtonBlock {
  label: string;
  url: string;
  align: 'left' | 'center';
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailDividerBlock".
 */
export interface EmailDividerBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'divider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailSpacerBlock".
 */
export interface EmailSpacerBlock {
  size: 'small' | 'medium' | 'large';
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'writer' | 'seo-manager' | 'reviewer' | 'publisher' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Machine identities for keyword research, generation, and import workflows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-accounts".
 */
export interface ServiceAccount {
  id: number;
  name: string;
  description?: string | null;
  scopes: (
    | 'content:read'
    | 'content:draft:create'
    | 'content:draft:update'
    | 'content:submit'
    | 'content:publish'
    | 'marketing:read'
    | 'marketing:draft:create'
    | 'marketing:draft:update'
    | 'marketing:test'
    | 'marketing:send'
    | 'jobs:read'
  )[];
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'service-accounts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-requests".
 */
export interface AutomationRequest {
  id: number;
  idempotencyKey: string;
  requestHash: string;
  operation: string;
  identity: string;
  statusCode: number;
  response:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'importContent' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'importContent' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'content-briefs';
        value: number | ContentBrief;
      } | null)
    | ({
        relationTo: 'marketing-email-templates';
        value: number | MarketingEmailTemplate;
      } | null)
    | ({
        relationTo: 'marketing-campaigns';
        value: number | MarketingCampaign;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'service-accounts';
        value: number | ServiceAccount;
      } | null)
    | ({
        relationTo: 'automation-requests';
        value: number | AutomationRequest;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'service-accounts';
        value: number | ServiceAccount;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'service-accounts';
        value: number | ServiceAccount;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  template?: T;
  workflowStatus?: T;
  publishedAt?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        callout?: T | CalloutBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        tool?: T | ToolBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        primaryQuery?: T;
        intent?: T;
        secondaryQueries?:
          | T
          | {
              query?: T;
              id?: T;
            };
        canonicalPath?: T;
        schemaType?: T;
        noIndex?: T;
        openGraphImage?: T;
      };
  provenance?:
    | T
    | {
        source?: T;
        workflowRunId?: T;
        model?: T;
        promptVersion?: T;
        sourceKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        generatedAt?: T;
        lastHumanEditAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  alignment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock_select".
 */
export interface CalloutBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  tone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  label?: T;
  href?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToolBlock_select".
 */
export interface ToolBlockSelect<T extends boolean = true> {
  toolKey?: T;
  heading?: T;
  description?: T;
  placement?: T;
  theme?: T;
  config?:
    | T
    | {
        inputLabel?: T;
        defaultKeyword?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  authors?:
    | T
    | {
        name?: T;
        id?: T;
      };
  workflowStatus?: T;
  publishedAt?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        callout?: T | CalloutBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        tool?: T | ToolBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        primaryQuery?: T;
        intent?: T;
        secondaryQueries?:
          | T
          | {
              query?: T;
              id?: T;
            };
        canonicalPath?: T;
        schemaType?: T;
        noIndex?: T;
        openGraphImage?: T;
      };
  provenance?:
    | T
    | {
        source?: T;
        workflowRunId?: T;
        model?: T;
        promptVersion?: T;
        sourceKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        generatedAt?: T;
        lastHumanEditAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        social?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-briefs_select".
 */
export interface ContentBriefsSelect<T extends boolean = true> {
  title?: T;
  locale?: T;
  status?: T;
  primaryKeyword?: T;
  secondaryKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  intent?: T;
  audience?: T;
  outline?: T;
  internalLinkTargets?: T;
  workflowRunId?: T;
  sourceData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-email-templates_select".
 */
export interface MarketingEmailTemplatesSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  logoUrl?: T;
  accentColor?: T;
  pageBackgroundColor?: T;
  contentBackgroundColor?: T;
  defaultFromName?: T;
  defaultReplyTo?: T;
  footerText?: T;
  companyAddress?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-campaigns_select".
 */
export interface MarketingCampaignsSelect<T extends boolean = true> {
  internalName?: T;
  campaignKey?: T;
  locale?: T;
  audienceTopic?: T;
  filterAudienceByLocale?: T;
  template?: T;
  subject?: T;
  preheader?: T;
  content?:
    | T
    | {
        heading?: T | EmailHeadingBlockSelect<T>;
        text?: T | EmailTextBlockSelect<T>;
        image?: T | EmailImageBlockSelect<T>;
        button?: T | EmailButtonBlockSelect<T>;
        divider?: T | EmailDividerBlockSelect<T>;
        spacer?: T | EmailSpacerBlockSelect<T>;
      };
  fromName?: T;
  replyTo?: T;
  workflowStatus?: T;
  scheduledAt?: T;
  launchStatus?: T;
  launchedAt?: T;
  recipientCount?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailHeadingBlock_select".
 */
export interface EmailHeadingBlockSelect<T extends boolean = true> {
  text?: T;
  level?: T;
  align?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailTextBlock_select".
 */
export interface EmailTextBlockSelect<T extends boolean = true> {
  text?: T;
  align?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailImageBlock_select".
 */
export interface EmailImageBlockSelect<T extends boolean = true> {
  url?: T;
  alt?: T;
  linkUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailButtonBlock_select".
 */
export interface EmailButtonBlockSelect<T extends boolean = true> {
  label?: T;
  url?: T;
  align?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailDividerBlock_select".
 */
export interface EmailDividerBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailSpacerBlock_select".
 */
export interface EmailSpacerBlockSelect<T extends boolean = true> {
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-accounts_select".
 */
export interface ServiceAccountsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  scopes?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-requests_select".
 */
export interface AutomationRequestsSelect<T extends boolean = true> {
  idempotencyKey?: T;
  requestHash?: T;
  operation?: T;
  identity?: T;
  statusCode?: T;
  response?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskImportContent".
 */
export interface TaskImportContent {
  input: {
    items:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    identity: string;
  };
  output: {
    results:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}